<style>
    .draft_btn{
        margin-left: 10px !important;
    }
    .ids{
        width: 20px;
    }
</style>
<div  class="ui container segment">
    <div class="field">
        <div class="ui six item stackable tabs menu" style="width:700px;margin-top: 15px;">
            <a class="item <?php echo $status === '' ? 'active' : ''; ?>" href="?status=">全部</a>
            <a class="item <?php echo $status === '0' ? 'active' : ''; ?>" href="?status=0">未配对</a>
            <a class="item <?php echo $status === '1' ? 'active' : ''; ?>" href="?status=1">匹配成功</a>
            <a class="item <?php echo $status === '4' ? 'active' : ''; ?>" href="?status=4">等待处理</a>
            <a class="item <?php echo $status === '2' ? 'active' : ''; ?>" href="?status=2">已保存草稿</a>
            <a class="item <?php echo $status == '200' ? 'active' : ''; ?>" href="?status=200">已上传</a>
        </div>
    </div>
    <button class="ui primary button" style="margin-top:10px;" onclick="addProducts();">批量添加</button><span id="cateSelect"></span><button class="ui primary button" style="margin-top:10px;" onclick="searchCateSelect();">搜索</button>
    <table class="ui celled striped table">
        <thead><tr><th style="text-align: center;width: 60px;"><a href="javascript:;" onclick="quanxuan();">全选</a></th><th style="text-align: center;width: 60px;">ID</th><th style="text-align: center;width: 100px;">创建时间</th><th style="text-align: center;">图片</th><th style="text-align: center;">标题</th><th style="text-align: center;width: 200px;">状态</th></tr></thead>
        <tbody>
            <?php
            foreach ($pages->items as $item) {
                $opt = '';
                if ($item['status'] == 1) {
                    $opt = '<button class="ui primary button draft_btn" onclick="sub_draft(' . $item['id'] . ');">保存草稿</button>';
                }
                echo '<tr aid="' . $item['id'] . '">
                    <td>' . ($item['status'] === '1' ? '<input type="checkbox" class="ids" value="' . $item['id'] . '">' : '') . '</td>
                    <td style="text-align: center;"><a href="/collection/data?id=' . $item['id'] . '" target="_blank">' . $item['id'] . '<br />查看</a></td>
                    <td style="text-align: center;">' . date('m-d H:i', strtotime($item['createtime'])) . '</td> 
                    <td style="text-align: center;"><a href="' . $item['source_url'] . '" target="_blank"><img src="' . $item['source_img'] . '" style="height:60px;margin:3px 10px;"/></a></td> 
                    <td style="text-align: center;"><a href="' . $item['source_url'] . '" target="_blank">' . $item['source_product_name'] . ($item['status'] == 0 ? '<span style="color:red;font-size:8px;">(' . (empty($item['need_attribute']) ? '分类|属性' : trim($item['need_attribute'], '|')) . '缺失)</span>' : '') . '</a></td> 
                    <td style="text-align: center;" class="opt_td">' . ($item['status'] == 200 ? '已上传' : ($item['status'] == 2 ? '<a href="http://seller.dhgate.com/syi/edit.do?prodDraftId=' . $item['dh_product_id'] . '&inp_catepubid=' . $item['dh_product_id'] . '&isdraftbox=1" target="_blank">查看草稿</a>' : ($item['status'] == 1 ? ($item['dh_product_id'] > 0 ? '<a href="http://seller.dhgate.com/syi/edit.do?prodDraftId=' . $item['dh_product_id'] . '&inp_catepubid=' . $item['dh_product_id'] . '&isdraftbox=1" target="_blank">查看草稿</a>(已重新匹配)' : '匹配成功') : ($item['status'] == 400 ? '放弃' : ($item['status'] == 4 ? '等待处理' : '未匹配'))))) . $opt . '</td> 
                </tr>';
            }
            ?>
        </tbody>
    </table>

    <div class="ui basic buttons">
        <span class="ui button"><?php echo "共 ", $pages->all_num, " 条记录 ", $pages->current, " / ", $pages->total_pages, " 页"; ?></span>
        <?php
        $base_url = preg_replace('/\&page=\d+/', '', $_SERVER['REQUEST_URI']);
        $first = "<a class='ui button' href='{$base_url}'>首页</a> ";
        $last = "<a class='ui button' href='{$base_url}&page={$pages->last}'>尾页</a> ";
        $prev_disable_class = $pages->current <= 1 ? 'disabled' : '';
        $prev = "<a class='ui button {$prev_disable_class}' href='{$base_url}&page={$pages->before}'>上一页</a> ";
        $next_disable_class = $pages->current >= $pages->total_pages ? 'disabled' : '';
        $next = "<a class='ui button {$next_disable_class}' href='{$base_url}&page={$pages->next}'>下一页</a> ";
        $list_pages = '';
        //每边显示inum个页码
        $inum = 3;
        if ($pages->current - $inum > 1)
            $list_pages.=" <a class='ui button disabled'>...</a> ";
        //左边的页码  
        for ($i = $inum; $i >= 1; $i--) {
            $p = $pages->current - $i;
            if ($p < 1) {
                continue;
            } else {
                $list_pages.=" <a class='ui button' href='{$base_url}&page={$p}'>{$p}</a> ";
            }
        }

        //当前页码  
        $list_pages.=" <a class='ui button active' href='{$base_url}&page={$pages->current}'>{$pages->current}</a>";
        //右边页码  
        for ($i = 1; $i <= $inum; $i++) {
            $p = $pages->current + $i;
            if ($p > $pages->total_pages) {
                break;
            } else {
                $list_pages.=" <a class='ui button' href='{$base_url}&page={$p}'>{$p}</a> ";
            }
        }
        if ($pages->current + $inum < $pages->total_pages)
            $list_pages.=" <a class='ui button disabled'>...</a> ";
        $pages_str = $first . $prev . $list_pages . $next . $last;
        if ($pages->total_pages > 1) {
            echo $pages_str;
        }
        ?>
    </div>
</div>
<script>
    $(function () {
        getCate(0);
    });
    function sub_draft(id) {
        $.ajax({
            url: '/product/draft',
            type: 'POST',
            dataType: 'json',
            async: false,
            data: {id: id},
            success: function (json) {
                var _this = $('tr[aid=' + id + '] .opt_td');
                if (json['status'] == 'success') {
                    _this.html('<span class="success"><a href="http://seller.dhgate.com/syi/edit.do?prodDraftId=' + json['data']['dh_product_id'] + '&inp_catepubid=' + json['data']['dh_category_id'] + '&isdraftbox=1" target="_blank">查看草稿</a></span>');
                } else {
                    _this.html('<span style="color:red;">保存失败</span>');
                }
            }
        });
    }

    function quanxuan() {
        $('.ids').prop('checked', true);
    }
    function addProducts() {
        var ids = [];
        $('.ids:checked').each(function () {
            var id = $(this).val();
            ids.push(id);
        });
        $.ajax({
            url: '/product/addProduct',
            type: 'POST',
            dataType: 'json',
            async: false,
            data: {ids: ids, content: '添加产品草稿'},
            success: function (json) {
                if (json['status'] == 'success') {
                    $('.ids:checked').each(function () {
                        $(this).parents('tr').find('.opt_td').html('<span class="success">等待处理</span>');
                    });
                }
                alert(json['msg']);
                $('.ids').prop('checked', false);
            }
        });
    }

    function getCate(catePubId) {
        $.ajax({
            url: '/product/getCateAttr',
            type: 'GET',
            dataType: 'json',
            data: {catePubId: catePubId},
            async: false,
            success: function (json) {
                if (json['data'] != null && json['data'] != '' && json['data'].length > 0) {
                    var html = '<span class="cateSpan selSpan" style="margin-right:5px;"><select class="cateSelectBox" onchange="cateChange($(this));" style="height: 30px;">';
                    html += '<option value="">请选择</option>';
                    $.each(json['data'], function (k, v) {
                        html += '<option value="' + v['catePubId'] + '">' + v['pubNameCn'] + '</option>';
                    });
                    html += '</select></span>';
                    $('#cateSelect').append(html);
                }
            }
        });
    }
    function cateChange(_this) {
        var catePubId = _this.val();
        removeNext(_this.parent('.cateSpan').next());
        getCate(catePubId);
    }
    function removeNext(_this) {
        if (_this.length > 0) {
            if (_this.next().length > 0) {
                removeNext(_this.next());
            }
            _this.remove();
        }
    }
    function searchCateSelect() {
        var url = '<?php echo preg_replace('/(\&page=\d+)|(\&catePubId=\d+)/', '', $_SERVER['REQUEST_URI']); ?>';
        var len = $('#cateSelect').find('.cateSelectBox').length;
        var cateId = $('.cateSelectBox').eq(len - 1).val();
        if (cateId == '' && len > 1) {
            cateId = $('.cateSelectBox').eq(len - 2).val();
        }
        url += '&catePubId=' + cateId;
        window.location.href = url;
    }
</script>