<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
        <title>敦煌管理后台</title>
        <link href="/css/semantic.2.0.8.css" rel="stylesheet">
        <script src="/js/jquery.min.1.7.2.js"></script>
        <script src="/js/semantic-2.0.7.min.js"></script>
        <style>
            .main.container {
                margin-top: 5em;
            }
        </style>
    </head>
    <body>
        <div class="ui fixed borderless menu">
            <div class="ui container">
                <div href="#" class="header item">
                    <img class="logo" src="/logo.jpg">
                    敦煌
                </div>
                <a href="/collection/index" class="item <?php echo (isset($_GET['_url']) && $_GET['_url'] == '/collection/index' ? 'active' : ''); ?>">采集</a>
                <a href="/lexicon/categoriesIndex" class="item <?php echo (isset($_GET['_url']) && $_GET['_url'] == '/lexicon/categoriesIndex' ? 'active' : ''); ?>">分类匹配</a>
                <a href="/lexicon/index" class="item <?php echo (isset($_GET['_url']) && $_GET['_url'] == '/lexicon/index' ? 'active' : ''); ?>">属性匹配</a>
                <a href="/lexicon/keyList" class="item <?php echo (isset($_GET['_url']) && $_GET['_url'] == '/lexicon/keyList' ? 'active' : ''); ?>">键值列表</a>
                <a href="/product/index" class="item <?php echo (isset($_GET['_url']) && $_GET['_url'] == '/product/index' ? 'active' : ''); ?>">产品保存</a>
                <a href="/setting/index" class="item <?php echo (isset($_GET['_url']) && $_GET['_url'] == '/setting/index' ? 'active' : ''); ?>">设置</a>
                <a href="javascript:;" class="item userSpan">
                    敦煌用户 ： 
                    <select class="userSelectBox" onchange="userChange($(this));" style="height: 30px;">
                        <?php foreach ($users as $k => $u) { ?>
                            <option value="<?php echo $k; ?>" <?php echo $k == $current_user ? 'selected="selected"' : ''; ?>><?php echo $k; ?></option>
                        <?php } ?>
                    </select>
                </a>
            </div>
        </div>
        <div class="ui main container">
            <?php $this->flash->output() ?>
            <?php echo $this->getContent(); ?>
        </div>
        <script>
            function userChange(_this) {
                var user = _this.val();
                $.ajax({
                    url: '/setting/setUser',
                    type: 'GET',
                    dataType: 'json',
                    data: {user: user},
                    async: false,
                    success: function (json) {
                        if (json['status'] != 'success') {
                            alert('用户设置错误');
                        } else {
                            window.location.reload();
                        }
                    }
                });
            }
        </script>
    </body>
</html>
